#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightGreen'
    template = '{{ .UserName }}'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightWhite'
    template = ': '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightBlue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'darkGray'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <lightCyan>{{ if gt .Behind 0 }}⇣ {{ end }}{{ if gt .Ahead 0 }}⇡ {{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}lightRed{{end}}",
      "{{if eq .Code 0}}lightMagenta{{end}}",
    ]
    background = 'transparent'
    template = '>'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}lightRed{{end}}",
    "{{if eq .Code 0}}lightMagenta{{end}}",
  ]
  background = 'transparent'
  template = '>'

[secondary_prompt]
  foreground = 'lightMagenta'
  background = 'transparent'
  template = '>>'
