console_title_template = '{{ .Folder }}'
version = 3
auto_upgrade = true
final_space = true

[secondary_prompt]
  template = '>>'
  foreground = 'lightMagenta'
  background = 'transparent'

[transient_prompt]
  template = '>'
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}lightRed{{end}}', '{{if eq .Code 0}}lightMagenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightYellow'
    template = '{{ if .Venv }}[{{ .Venv }}] {{ end }}'

    [blocks.segments.properties]
      display_mode = 'environment'
      fetch_virtual_env = true
      home_enabled = true

  [[blocks.segments]]
    type = 'kubectl'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightBlue'
    template = '{{ if .Namespace }}({{ .Namespace }}) {{ end }}'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .UserName }}'
    foreground = 'lightGreen'
    background = 'transparent'
    type = 'session'

  [[blocks.segments]]
    style = 'plain'
    template = ': '
    foreground = 'lightWhite'
    background = 'transparent'
    type = 'text'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'lightBlue'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <lightCyan>{{ if gt .Behind 0 }}⇣ {{ end }}{{ if gt .Ahead 0 }}⇡ {{ end }}</>'
    foreground = 'darkGray'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '>'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}lightRed{{end}}', '{{if eq .Code 0}}lightMagenta{{end}}']
